### ISSUE TITLE
NameError: name 'train_test_split' is not defined

### ISSUE THREAD

**Issue by mables** [faizann24/Using-machine-learning-to-detect-maclicious-URLs#2]
Hello, I am getting the below error when I try to run script.py 

$ python script.py 
Traceback (most recent call last):
  File "script.py", line 39, in <module>
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)   #split into training and testing set 80/20 ratio
NameError: name 'train_test_split' is not defined

Unsure of how to proceed, any direction or input would be much appreciated.
Thank you, mables

**Comment by faizann24** [comment]
from sklearn.cross_validation import train_test_split

Add this and it will resolve the issue.

Best Regards.

**Comment by mables** [comment]
Success! Thank you Faizan!

**Comment by khushi-singh** [comment]
after adding  from sklearn.cross_validation import train_test_split
its showing 
No module named 'sklearn.cross_validation'
how can I resolve it ?

**Comment by SakanL** [comment]
try changing cross_validation to model_selection
It's from deprecation of cross_validation

**Comment by khushi-singh** [comment]
Both not working neither model_selection nor cross_validation
![Screenshot (4)](https://user-images.githubusercontent.com/67220499/97070621-a43e0780-158e-11eb-97ff-47e45c8c9422.png)
see these are the errors showing on both.
I will be really glad if you help.

**Comment by khushi-singh** [comment]
Thank you all for your help

**Comment by rajeshkusuma** [comment]
After changing to model_selection

I am getting the following error. Please help.

ImportError: cannot import name 'delayed' from 'sklearn.utils.fixes' (C:\Users\rajesh_kusuma\anaconda3\lib\site-packages\sklearn\utils\fixes.py)

**Comment by AkshatSingh-spx** [comment]
after doing this step error cross validation not define and same as model selection from sklearn.cross_validation import train_test_split 
try changing cross_validation to model_selection
help me anyone

**Comment by CLAUDERNORONHA** [comment]
Thank you !!!

**Comment by Aman-sh1** [comment]
NameError                                 Traceback (most recent call last)
<ipython-input-15-ef91596f6096> in <module>
      1 svc_classifier = SVC(kernel = 'rbf', random_state =0)
----> 2 svc_classifier.fit(xtrain, ytrain)

NameError: name 'xtrain' is not defined

**Comment by Aman-sh1** [comment]
plz help me in solving this

**Comment by AkshatSingh-spx** [comment]
Try to use sklearn model

**Comment by Aman-sh1** [comment]
how ?
means plz tell me in detail

**Comment by AkshatSingh-spx** [comment]
Ok, I will check.

Refer this

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
