### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ahmedak** [faizann24/Using-machine-learning-to-detect-maclicious-URLs#4]
The link given in readme http://fsecurify.com/using-machine-learning-detect-malicious-urls/ is broken

**Comment by leni1** [comment]
@ahmedak try checking it out on the Internet archive here: https://web.archive.org/web/20170514093208/http://fsecurify.com/using-machine-learning-detect-malicious-urls/

**Comment by ahmedak** [comment]
@leni1 thanks :smile:
